# Generated by Django 2.0.7 on 2018-09-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('General', 'General')], max_length=13),
        ),
    ]
