# Generated by Django 2.0.7 on 2018-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180906_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image',
        ),
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
