# Generated by Django 2.0.7 on 2018-09-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180906_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='description',
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
