# Generated by Django 2.0.7 on 2018-09-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180906_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Post',
            new_name='post',
        ),
    ]
