# Generated by Django 2.0.7 on 2018-09-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180906_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='index.JPG', upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(default='', max_length=100),
        ),
    ]
