# Generated by Django 2.0.7 on 2019-07-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180917_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='Heading',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='Picture',
            field=models.ImageField(null=True, upload_to='blog_pictures'),
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(default='', max_length=50),
        ),
    ]
