# Generated by Django 2.0.7 on 2018-08-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
