# Generated by Django 2.0.7 on 2018-08-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron2', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
