# Generated by Django 2.0.7 on 2018-08-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iron2', '0004_auto_20180824_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Image',
            new_name='image',
        ),
    ]
