# Generated by Django 2.0.7 on 2018-08-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iron2', '0005_auto_20180830_1216'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
