# Generated by Django 2.0.7 on 2018-08-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron2', '0006_auto_20180830_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Mobile',
            field=models.IntegerField(default='00'),
        ),
    ]
