# Generated by Django 2.0.7 on 2018-09-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron2', '0008_auto_20180908_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
