# Generated by Django 2.0.7 on 2018-09-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron2', '0009_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, upload_to='documents/'),
        ),
    ]
