# Generated by Django 2.0.7 on 2018-09-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron2', '0010_auto_20180913_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(default='profile_image/elder.JPG', upload_to='documents/'),
        ),
    ]
