# Generated by Django 2.0.7 on 2018-10-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iron2', '0012_auto_20180918_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_name',
            new_name='Filename',
        ),
    ]
